### ISSUE TITLE
Can we use weakref.WeakMethod?

### ISSUE THREAD

**Issue by Korijn** [Korijn/observ#106]
Is `weakref.WeakMethod` useful for our weak references to bound methods?

@berendkleinhaneveld

**Comment by berendkleinhaneveld** [comment]
Probably a good idea indeed! 

Btw: it also can't handle the way PySide treats methods on QObjects:
```
>>> from PySide6 import QtWidgets
>>> app = QtWidgets.QApplication()
>>> from weakref import WeakMethod
>>> class Toet(QtWidgets.QLabel):
...     pass
...
>>> toet = Toet()
>>> w = WeakMethod(toet.setText)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cg/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/weakref.py", line 52, in __new__
    raise TypeError("argument should be a bound method, not {}"
TypeError: argument should be a bound method, not <class 'builtin_function_or_method'>
>>>
```

**Comment by Korijn** [comment]
I tried this, and it does work, but in order to make the tests pass I have to add `gc.collect()` statements.

E.g. in `test_no_strong_reference_to_callback` I have to add

```py
    state["count"] += 1

    assert Counter.count_a == 1
    assert Counter.count_b == 1
    assert Counter.count_c == 1

    del counter
    gc.collect()  # <<< this line

    state["count"] += 1

    assert Counter.count_a == 1
    assert Counter.count_b == 1
    assert Counter.count_c == 1
```

I'm not sure if I'm a fan now :/ it seems it does work _eventually_ but the WeakMethod object still returns the callback after `del counter` if we don't force `gc.collect()` to run immediately.
